require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

target 'NativeNebulaHost' do
  use_react_native!(
    :path => '../../../node_modules/react-native',
    :app_path => File.expand_path('..', __dir__)
  )

  pod 'NebulaHost', :path => File.expand_path('../../../packages/host', __dir__)

  post_install do |installer|
    react_native_post_install(
      installer,
      '../../../node_modules/react-native',
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |configuration|
        configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
  end
end

post_integrate do |installer|
  installer.pods_project.targets.each do |target|
    next unless target.name == 'fmt'

    target.build_configurations.each do |configuration|
      configuration.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
    end
  end
  installer.pods_project.save
end
